// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// DATABASE_URL is optional during prisma generate (only needed for migrations)
// Use process.env directly to avoid throwing errors during build
const databaseUrl = process.env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Only set url if DATABASE_URL is available
    // For prisma generate, this can be a placeholder
    // For migrations, DATABASE_URL must be set in environment
    url: databaseUrl || "postgresql://user:password@localhost:5432/dbname",
  },
});
